//! Opaque native session contract (FEAT-005 "Opaque session").
//!
//! The WebView receives only an unpredictable, in-memory, epoch-bound opaque
//! handle. Rust retains decrypted credentials inside native secret containers
//! (Phase 4 authority). Handles are never persisted, logged, copied into
//! navigation/history, or transferred.

use serde::{Deserialize, Serialize};

/// Monotonic epoch. Every Lock/removal/replacement/native-failure/ownership
/// loss/identity-invalidation boundary increments the epoch and revokes every
/// handle of the previous epoch.
#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Serialize, Deserialize)]
#[serde(transparent)]
pub struct SessionEpoch(pub u64);

impl SessionEpoch {
    pub fn next(self) -> Self {
        Self(self.0.wrapping_add(1))
    }
}

/// Opaque session handle: unpredictable random bytes bound to an epoch and the
/// main window. Not persisted; not logged; no secret material inside.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
pub struct SessionHandle {
    pub epoch: SessionEpoch,
    /// 16 random bytes (generated by the Phase 4 authority with the approved
    /// OS CSPRNG). Opaque to the WebView.
    #[serde(with = "bytes_hex")]
    pub opaque: [u8; 16],
    /// Caller identity: only the main window is an allowed runtime target.
    pub main_window_only: bool,
}

mod bytes_hex {
    use serde::{Deserialize, Deserializer, Serializer};

    pub fn serialize<S>(bytes: &[u8; 16], serializer: S) -> Result<S::Ok, S::Error>
    where
        S: Serializer,
    {
        let mut out = String::with_capacity(32);
        for b in bytes {
            out.push_str(&format!("{b:02x}"));
        }
        serializer.serialize_str(&out)
    }

    pub fn deserialize<'de, D>(deserializer: D) -> Result<[u8; 16], D::Error>
    where
        D: Deserializer<'de>,
    {
        let s = String::deserialize(deserializer)?;
        if s.len() != 32 {
            return Err(serde::de::Error::custom(
                "opaque handle must be 32 hex chars",
            ));
        }
        let mut out = [0u8; 16];
        for i in 0..16 {
            let hex = &s[i * 2..i * 2 + 2];
            out[i] = u8::from_str_radix(hex, 16).map_err(serde::de::Error::custom)?;
        }
        Ok(out)
    }
}

impl SessionHandle {
    pub fn is_valid_for_epoch(&self, epoch: SessionEpoch) -> bool {
        self.epoch == epoch && self.main_window_only
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn handle_round_trips_as_hex_without_leaking() {
        let handle = SessionHandle {
            epoch: SessionEpoch(3),
            opaque: [0xAB; 16],
            main_window_only: true,
        };
        let json = serde_json::to_string(&handle).unwrap();
        assert!(json.contains("abababababababababababababababab"));
        let back: SessionHandle = serde_json::from_str(&json).unwrap();
        assert_eq!(handle, back);
    }

    #[test]
    fn epoch_binds_handle() {
        let handle = SessionHandle {
            epoch: SessionEpoch(1),
            opaque: [7; 16],
            main_window_only: true,
        };
        assert!(handle.is_valid_for_epoch(SessionEpoch(1)));
        assert!(!handle.is_valid_for_epoch(SessionEpoch(2)));
        let mut other = handle.clone();
        other.main_window_only = false;
        assert!(!other.is_valid_for_epoch(SessionEpoch(1)));
    }

    #[test]
    fn malformed_handle_hex_is_rejected() {
        let json = r#"{"epoch":1,"opaque":"zzzz","mainWindowOnly":true}"#;
        assert!(serde_json::from_str::<SessionHandle>(json).is_err());
    }

    #[test]
    fn unknown_handle_fields_are_rejected() {
        let json = r#"{"epoch":1,"opaque":"abababababababababababababababab","mainWindowOnly":true,"persist":true}"#;
        assert!(serde_json::from_str::<SessionHandle>(json).is_err());
    }
}
