//! Pinned tonic gRPC client (FEAT-005 "Pinned Rust gRPC client").
//!
//! Generated by `build.rs` from the digest-pinned HushServerNode protocol
//! artifacts (`conformance/protocol/`; build fails on digest mismatch). Only
//! the EPIC-001 identity lookup surface is exposed through `IdentityLookup`;
//! the blockchain service code is generated but NOT exposed here. Platform-
//! trusted TLS certificates are used in production (`tls-native-roots`);
//! cleartext exists only in explicit development composition. Arbitrary
//! URLs, credentials, headers, and unapproved redirects are impossible by
//! construction (closed endpoint vocabulary).

use tonic::transport::{Channel, ClientTlsConfig};

use super::{Endpoint, IdentityLookup, PublicProfile, TransportFailure};

// Generated tonic/prost code for package `rpcHush` (identity + blockchain).
// The build script verifies the protocol artifacts' pinned SHA-256 first.
include!(concat!(env!("OUT_DIR"), "/rpcHush.hushIdentity.rs"));

/// Immutable protocol file-descriptor set generated at build time. The
/// descriptor digest is stable for the pinned protocol revision and is
/// asserted in tests so a protocol change fails the gate.
pub fn protocol_descriptor_set() -> &'static [u8] {
    include_bytes!(concat!(env!("OUT_DIR"), "/protocol.bin"))
}

/// Real gRPC identity lookup over the pinned generated client.
pub struct GrpcIdentityLookup {
    client: hush_identity_client::HushIdentityClient<Channel>,
}

impl GrpcIdentityLookup {
    /// Connect to a resolved closed endpoint. TLS uses platform-trusted
    /// native roots for production; cleartext only for explicit development
    /// endpoints. The connection itself never performs secret work.
    pub async fn connect(endpoint: &Endpoint) -> Result<Self, TransportFailure> {
        let base = Channel::from_shared(endpoint.url().to_string())
            .map_err(|_| TransportFailure::Unavailable)?;
        let channel = if endpoint.is_tls() {
            let tls = ClientTlsConfig::new().with_native_roots();
            base.tls_config(tls)
                .map_err(|_| TransportFailure::Unavailable)?
        } else {
            base
        };
        let channel = channel.connect().await.map_err(|_| TransportFailure::Unavailable)?;
        Ok(Self {
            client: hush_identity_client::HushIdentityClient::new(channel),
        })
    }
}

impl IdentityLookup for GrpcIdentityLookup {
    async fn get_identity(
        &mut self,
        signing_address: &str,
    ) -> Result<Option<PublicProfile>, TransportFailure> {
        let request = tonic::Request::new(GetIdentityRequest {
            public_signing_address: signing_address.to_string(),
        });
        let reply = self
            .client
            .get_identity(request)
            .await
            .map_err(|_| TransportFailure::Unavailable)?
            .into_inner();
        if !reply.successfull {
            return Ok(None);
        }
        Ok(Some(PublicProfile {
            display_name: reply.profile_name,
            signing_address: reply.public_signing_address,
            encrypt_address: reply.public_encrypt_address,
            is_public: reply.is_public,
        }))
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::ubuntu_vault::crypto::encoding::hex_encode;
    use sha2::{Digest, Sha256};

    #[test]
    fn protocol_descriptor_is_stable_for_pinned_revision() {
        // The descriptor set derives from the digest-pinned protos; its hash
        // is a regression lock — a protocol change (or build-script drift)
        // fails this gate before any release.
        let mut hasher = Sha256::new();
        hasher.update(protocol_descriptor_set());
        let digest = hex_encode(&hasher.finalize());
        assert_eq!(digest.len(), 64);
        // Pinned value (computed at build of the pinned revision):
        assert_eq!(
            digest,
            "5d951400847a2190c3df69aa21df7fce8c6ca71b74fdc1020512a67dc921b5b3"
        );
    }
}
