import AuthRoot from './auth/AuthRoot';
import { connection } from 'next/server';

/**
 * Root application page.
 *
 * FEAT-002 replaces the foundation screen with the auth-gated root: the
 * branded Sovereign Shield renders immediately; protected content mounts only
 * after local unlock + exact online identity verification. The visible URL
 * remains `/`; no election/workflow identifier is exposed here.
 */
export default async function HomePage() {
  // The standalone web runtime must render per request so Next.js can attach
  // the CSP nonce generated by `src/proxy.ts`. Tauri's static export has no
  // request boundary and keeps its existing build-time CSP handling.
  if (process.env.STATIC_EXPORT !== 'true') {
    await connection();
  }
  return <AuthRoot />;
}
