#!/usr/bin/env node
/**
 * FEAT-010 worker bundle builder (Task 7.3).
 *
 * Bundles the production SharedWorker entry (`src/lib/browser-vault/production/
 * worker-entry.ts`) into `public/workers/vault-shared-worker.js` with esbuild
 * (first-party, same-origin, no CDN). The bundle is a self-contained ES module
 * that boots the sealed vault authority when the worker global loads:
 *
 *   self.bootHushVaultWorker({ appVersion, buildDigest })
 *
 * The build is deterministic and locked (esbuild is a pinned transitive
 * dependency of Next.js; the worker bundle never imports page/React code).
 *
 * Usage: node scripts/build-worker.mjs [--watch]
 */
import { build } from 'esbuild';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';
import { mkdirSync } from 'node:fs';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
const ENTRY = join(ROOT, 'src/lib/browser-vault/production/worker-entry.ts');
const OUT_DIR = join(ROOT, 'public/workers');
const OUT_FILE = join(OUT_DIR, 'vault-shared-worker.js');

const watch = process.argv.includes('--watch');

mkdirSync(OUT_DIR, { recursive: true });

const options = {
  entryPoints: [ENTRY],
  outfile: OUT_FILE,
  bundle: true,
  format: 'esm',
  platform: 'browser',
  target: ['es2022'],
  minify: false,
  sourcemap: false,
  logLevel: 'info',
  banner: {
    js: '/* FEAT-010 production vault SharedWorker bundle — generated by scripts/build-worker.mjs. Never edit by hand. */',
  },
};

if (watch) {
  await build({ ...options, watch: true });
  console.log(`watching → ${OUT_FILE}`);
} else {
  await build(options);
  console.log(`built → ${OUT_FILE}`);
}
